package com.yoyofurniture.gui.administrator;

import com.yoyofurniture.bean.Administrator;
import com.yoyofurniture.bean.Gender;
import com.yoyofurniture.utility.HandleAccount;
import com.yoyofurniture.utility.ID;

import javax.swing.*;
import java.time.LocalDate;


public class AdmManageSpAdd extends javax.swing.JFrame {
    private static AdmManageSpAdd currentInstance;
    private String[] newID;


    private AdmManageSpAdd() {
        initComponents();
        selfInitComponents();
    }

    /**
     * Singleton structure
     * @return AdmManageSpAdd
     */
    public static AdmManageSpAdd initiateAdmManageSpAdd() {
        if (currentInstance == null) {
            currentInstance = new AdmManageSpAdd();
        }
        return currentInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldRe = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabelWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel4.setText("Name");

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel5.setText("Email");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        jLabel7.setText("Re-Enter Password");

        jTextFieldId.setEditable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Salesperson");

        jLabel2.setText("ID");

        jLabel3.setText("Phone");

        jLabel8.setText("Gender");

        jLabel9.setText("Date of Birth");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>());

        jDateChooser.setDateFormatString("dd/MM/yyyy");

        jLabelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWarning.setMinimumSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jButtonClear)
                .addGap(66, 66, 66)
                .addComponent(jButtonAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldId)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jTextFieldPhone)
                    .addComponent(jTextFieldName)
                    .addComponent(jPasswordFieldPass)
                    .addComponent(jPasswordFieldRe)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(297, 297, 297))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldName))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPhone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEmail))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordFieldPass))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordFieldRe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonAdd))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldName.setText("");
        jComboBoxGender.setSelectedItem(Gender.MALE);
        jDateChooser.setDate(HandleAccount.convertLocalDateToDate(LocalDate.now().minusYears(18)));
        jTextFieldPhone.setText("");
        jTextFieldEmail.setText("");
        jPasswordFieldPass.setText("");
        jPasswordFieldRe.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String id = newID[1];
        String name = jTextFieldName.getText();
        String gender = String.valueOf(jComboBoxGender.getSelectedItem());
        LocalDate birthDate = HandleAccount.convertDateToLocalDate(jDateChooser.getDate());
        String password = String.valueOf(jPasswordFieldPass.getPassword());
        String phone = jTextFieldPhone.getText();
        String email = jTextFieldEmail.getText();

        if (!validateInformation(name, birthDate, phone, email, password)){
            return;
        }

        String dateOfBirth = HandleAccount.localDateToString(birthDate);
        String[] newUser = {id, HandleAccount.hashString(password), name, gender, dateOfBirth, phone, email};
        String user = String.join(",", newUser);

        try {
            Administrator.addSp(user, newID);
        } catch (Exception e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(this, "Account created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        try {
            newID = HandleAccount.generateNewID(ID.SALESPERSON_ID);
            jTextFieldId.setText(newID[ID.SALESPERSON_ID.getIndex()]);
        } catch (Exception e) {
            e.printStackTrace();
        }

        jButtonClearActionPerformed(evt);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        currentInstance = null;
    }//GEN-LAST:event_formWindowClosed


    /**
     * Validate salesperson information
     * @param name name
     * @param birthDate date of birth
     * @param phone phone
     * @param email email
     * @param password password
     * @return true if all information correct, vice versa
     */
    private boolean validateInformation(String name, LocalDate birthDate, String phone, String email, String password) {
        if (name.isEmpty()) {
            jLabelWarning.setText("Please enter proper name");
        } else if (!HandleAccount.validateBOD(birthDate, 18)) {
            jLabelWarning.setText("The age of salesperson must be 18 or above.");
        } else if (!HandleAccount.validatePhone(phone)) {
            jLabelWarning.setText("Please enter valid Malaysia phone number");
        } else if (!HandleAccount.validateEmail(email)) {
            jLabelWarning.setText("Please enter valid email");
        } else if (!HandleAccount.validateNewPassword(password)) {
            jLabelWarning.setText("The new password must be at least 8 characters with 1 Capital Letter and 1 symbol");
        } else if (!HandleAccount.comparePassword(password, String.valueOf(jPasswordFieldRe.getPassword()))) {
            jLabelWarning.setText("Re-enter password does not match new password");
        } else {
            return true; // Validation passed
        }

        return false; // Validation failed
    }
    private void selfInitComponents() {
        try {
            newID = HandleAccount.generateNewID(ID.SALESPERSON_ID);
            jTextFieldId.setText(newID[ID.SALESPERSON_ID.getIndex()]);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        setTitle("Add Salesperson Account");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        jComboBoxGender.addItem(Gender.MALE);
        jComboBoxGender.addItem(Gender.FEMALE);
        jDateChooser.setDate(HandleAccount.convertLocalDateToDate(LocalDate.now().minusYears(18)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JComboBox<Gender> jComboBoxGender;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JPasswordField jPasswordFieldRe;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
