package com.yoyofurniture.gui.administrator;

import com.yoyofurniture.bean.Administrator;
import com.yoyofurniture.utility.HandleAccount;
import java.awt.Component;

import javax.swing.*;

/**
 * Admin edit personal profile page
 */
public class AdmManagePersonal extends javax.swing.JPanel {
    private final Administrator administrator;

    public AdmManagePersonal(Administrator administrator) {
        this.administrator = administrator;
        initComponents();
        selfInitComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jPasswordFieldCurrent = new javax.swing.JPasswordField();
        jPasswordFieldNew = new javax.swing.JPasswordField();
        jPasswordFieldReEnter = new javax.swing.JPasswordField();
        jButtonDiscard = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jToggleButtonEnablePass = new javax.swing.JToggleButton();
        jLabelWarning = new javax.swing.JLabel();
        jButtonMenu = new javax.swing.JButton();
        jResetButton1 = new javax.swing.JButton();

        jLabel1.setText("ID");

        jTextFieldId.setEditable(false);

        jLabel2.setText("Enter Current Password");

        jLabel3.setText("Name");

        jLabel4.setText("Re-Enter New Password");

        jLabel5.setText("Enter New Password");

        jPasswordFieldCurrent.setEditable(false);

        jPasswordFieldNew.setEditable(false);

        jPasswordFieldReEnter.setEditable(false);

        jButtonDiscard.setText("Discard Changes");
        jButtonDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscardActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save Changes");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jToggleButtonEnablePass.setText("Change Password");
        jToggleButtonEnablePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEnablePassActionPerformed(evt);
            }
        });

        jButtonMenu.setText("Menu");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jResetButton1.setText("Reset Fields");
        jResetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDiscard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(jResetButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButtonEnablePass)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPasswordFieldCurrent)
                                            .addComponent(jPasswordFieldNew)
                                            .addComponent(jPasswordFieldReEnter)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldName)
                                            .addComponent(jTextFieldId))))))))
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonMenu)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldId))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldName))
                .addGap(22, 22, 22)
                .addComponent(jToggleButtonEnablePass)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldCurrent))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldNew))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldReEnter))
                .addGap(24, 24, 24)
                .addComponent(jLabelWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDiscard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResetButton1))
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        jLabelWarning.setText("");

        String userID = jTextFieldId.getText();
        String name = jTextFieldName.getText();
        String oldPassword = String.valueOf(jPasswordFieldCurrent.getPassword());
        String newPassword = String.valueOf(jPasswordFieldNew.getPassword());
        String rePassword = String.valueOf(jPasswordFieldReEnter.getPassword());

        boolean changePass = jToggleButtonEnablePass.isSelected();

        try {
            if (!validateInformation(changePass, userID, name, oldPassword, newPassword, rePassword)) {
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        String[] newInfo = {userID, rePassword, name};
        Administrator.savePersonal(newInfo, changePass, administrator);

        // Modify current user data
        administrator.setUserID(userID);
        if (changePass) {
            administrator.setPassword(HandleAccount.hashString(rePassword));
        }
        administrator.setName(name);

        selfInitComponents();
        setPasswordField(false);

        JOptionPane.showMessageDialog(this, "Profile saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscardActionPerformed
        int confirmation = JOptionPane.showOptionDialog(
                AdmManagePersonal.this,
                "Are you sure you want to discard changes?",
                "Discard Changes",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                new String[]{"Confirm", "Cancel"},
                "Confirm"
        );
        
        if (confirmation == JOptionPane.YES_OPTION) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            if (frame != null) {
                frame.getContentPane().removeAll();
                frame.setContentPane(new AdmMain(administrator));
                frame.getContentPane().revalidate();
                frame.getContentPane().repaint();
            }
        } else {
            ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
        }
    }//GEN-LAST:event_jButtonDiscardActionPerformed

    private void jToggleButtonEnablePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEnablePassActionPerformed
        setPasswordField(jToggleButtonEnablePass.isSelected());
    }//GEN-LAST:event_jToggleButtonEnablePassActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.getContentPane().removeAll();
            frame.setContentPane(new AdmMain(administrator));
            frame.getContentPane().revalidate();
            frame.getContentPane().repaint();
        }
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jResetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButton1ActionPerformed
        selfInitComponents();
        jToggleButtonEnablePass.setSelected(false);
        setPasswordField(false);
        jLabelWarning.setText("");
    }//GEN-LAST:event_jResetButton1ActionPerformed


    /**
     * validate the information
     * @param changePass is change password enable?
     * @param userID user id
     * @param name name
     * @param oldPassword old password
     * @param newPassword new password
     * @param rePassword re-enter password
     * @return true if all information correct, vice versa
     * @throws Exception exception
     */
    private boolean validateInformation(boolean changePass, String userID, String name, String oldPassword, String newPassword, String rePassword) throws Exception {
        // Check Repeated User ID
        if (HandleAccount.checkRepeatedElement("administrator.txt", administrator.getUserID(), userID, 0)) {
            jLabelWarning.setText("User ID is taken by another account. Please use another userID.");
            return false;
        } else if (name.isEmpty()) {
            jLabelWarning.setText("Please enter proper name");
            return false;
        }

        // Password Validation
        if (changePass) {
            return validatePassword(oldPassword, newPassword, rePassword);
        }
        return true;
    }

    /**
     * Validate password format, and make sure re-enter password match to new password
     * @param oldPassword old password
     * @param newPassword new password
     * @param rePassword re-enter password
     * @return true if all correct, vice versa
     */
    private boolean validatePassword(String oldPassword, String newPassword, String rePassword) {
        if (!administrator.getPassword().equals(HandleAccount.hashString(oldPassword))) {
            jLabelWarning.setText("Current Password is incorrect.");
        } else if (!HandleAccount.validateNewPassword(newPassword)) {
            jLabelWarning.setText("The new password must be at least 8 characters, 1 Capital Letter, and 1 symbol.");
        } else if (!HandleAccount.comparePassword(newPassword, rePassword)) {
            jLabelWarning.setText("Re-enter password does not match new password.");
        } else {
            return true;
        }
        return false; // Password validation passed
    }

    /**
     * setEnable of password field
     * @param set true to enable, false to disable
     */
    private void setPasswordField(boolean set) {
        jPasswordFieldCurrent.setEditable(set);
        jPasswordFieldNew.setEditable(set);
        jPasswordFieldReEnter.setEditable(set);

        jPasswordFieldCurrent.setText("");
        jPasswordFieldNew.setText("");
        jPasswordFieldReEnter.setText("");
    }

    private void selfInitComponents() {
        jTextFieldId.setText(administrator.getUserID());
        jTextFieldName.setText(administrator.getName());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiscard;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPasswordField jPasswordFieldCurrent;
    private javax.swing.JPasswordField jPasswordFieldNew;
    private javax.swing.JPasswordField jPasswordFieldReEnter;
    private javax.swing.JButton jResetButton1;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JToggleButton jToggleButtonEnablePass;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
