/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.yoyofurniture.gui.officer;

import com.yoyofurniture.bean.Customer;
import com.yoyofurniture.bean.Invoice;
import com.yoyofurniture.bean.Officer;
import com.yoyofurniture.bean.SaleOrder;
import com.yoyofurniture.bean.SaleReport;
import com.yoyofurniture.bean.Salesperson;
import com.yoyofurniture.bean.Status;
import com.yoyofurniture.bean.WorkDoneReport;
import static com.yoyofurniture.bean.WorkDoneReport.generateWorkDoneReport;
import com.yoyofurniture.utility.HandleAccount;
import com.yoyofurniture.utility.HandleSales;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDate;
import java.time.Month;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author petywh
 */
public class OfcGenerateReport extends javax.swing.JFrame {
    private SaleOrder saleOrder;
    private Customer customer;
    private Salesperson salesperson;
    private final Officer officer;
    /**
     * Creates new form OfcGenerateReport
     */
    public OfcGenerateReport(Officer officer) {
        this.officer = officer;
        initComponents();
        
        selfInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxInvoice = new javax.swing.JComboBox<>();
        jGenerateInvoice = new javax.swing.JButton();
        jInvoiceError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>(new String[]{
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        });
        jGenerateWorkDone = new javax.swing.JButton();
        jWorkDoneError = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMonth1 = new javax.swing.JComboBox<>(new String[]{
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        });
        jGenerateApproved = new javax.swing.JButton();
        jWorkDoneError1 = new javax.swing.JLabel();
        jComboBoxYear1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxMonth2 = new javax.swing.JComboBox<>(new String[]{
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        });
        jGenerateClosed = new javax.swing.JButton();
        jWorkDoneError2 = new javax.swing.JLabel();
        jComboBoxYear2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(734, 104));

        jLabel1.setText("Invoice:");

        jLabel2.setText("Select Sales Order ID:");

        jComboBoxInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInvoiceActionPerformed(evt);
            }
        });

        jGenerateInvoice.setText("Generate Invoice");
        jGenerateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateInvoiceActionPerformed(evt);
            }
        });

        jInvoiceError.setForeground(new java.awt.Color(255, 51, 51));
        jInvoiceError.setText("<error-message>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInvoiceError, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jGenerateInvoice)))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenerateInvoice))
                .addGap(5, 5, 5)
                .addComponent(jInvoiceError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(734, 104));

        jLabel3.setText("Work Done Report:");

        jLabel4.setText("Select Month & Year:");

        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });

        jGenerateWorkDone.setText("Generate Report");
        jGenerateWorkDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateWorkDoneActionPerformed(evt);
            }
        });

        jWorkDoneError.setForeground(new java.awt.Color(255, 51, 51));
        jWorkDoneError.setText("<error-message>");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWorkDoneError, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jGenerateWorkDone)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenerateWorkDone)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jWorkDoneError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(734, 104));

        jLabel5.setText("Approved Sales Report:");

        jLabel6.setText("Select Month & Year:");

        jComboBoxMonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonth1ActionPerformed(evt);
            }
        });

        jGenerateApproved.setText("Generate Report");
        jGenerateApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateApprovedActionPerformed(evt);
            }
        });

        jWorkDoneError1.setForeground(new java.awt.Color(255, 51, 51));
        jWorkDoneError1.setText("<error-message>");

        jComboBoxYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWorkDoneError1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jGenerateApproved)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenerateApproved)
                    .addComponent(jComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jWorkDoneError1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMinimumSize(new java.awt.Dimension(734, 104));

        jLabel7.setText("Closed Sales Report:");

        jLabel8.setText("Select Month & Year:");

        jComboBoxMonth2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonth2ActionPerformed(evt);
            }
        });

        jGenerateClosed.setText("Generate Report");
        jGenerateClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateClosedActionPerformed(evt);
            }
        });

        jWorkDoneError2.setForeground(new java.awt.Color(255, 51, 51));
        jWorkDoneError2.setText("<error-message>");

        jComboBoxYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWorkDoneError2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBoxMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jGenerateClosed)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenerateClosed)
                    .addComponent(jComboBoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jWorkDoneError2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jLabel9.setText("Generate Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInvoiceActionPerformed
        
    }//GEN-LAST:event_jComboBoxInvoiceActionPerformed

    private void jGenerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateInvoiceActionPerformed
        try {
            String selectedSaleOrderID = (String) jComboBoxInvoice.getSelectedItem();
            SaleOrder selectedsaleOrder = HandleSales.getSaleOrderByID(selectedSaleOrderID);
            
            if(validateOrderStatus(selectedsaleOrder)){
                jInvoiceError.setText("");
                Invoice invoice = new Invoice(selectedsaleOrder);
                try {
                    salesperson = HandleAccount.readAllData("salesperson.txt", userinfo -> new Salesperson(userinfo[0], userinfo[1],
                            userinfo[2], userinfo[3], userinfo[4], userinfo[5], userinfo[6]), ","
                    ).stream().filter(user -> user.getUserID().equals(selectedsaleOrder.getSalesperson())).findFirst()
                            .map(user -> (Salesperson)user).get();
                    customer = HandleAccount.readAllData("customer.txt", userinfo -> new Customer(userinfo[0], userinfo[1],
                            userinfo[2], userinfo[3]), "\\|"
                    ).stream().filter(user -> user.getUserID().equals(selectedsaleOrder.getCustomer())).findFirst()
                            .map(user -> (Customer)user).get();
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                try {
                    invoice.generateInvoice(salesperson,customer);
                        int confirmation = JOptionPane.showOptionDialog(this,"Invoice Successfully created!","Message",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,new String[]{"Open in Folder", "Close"},"Close");
        
                    if (confirmation == JOptionPane.YES_OPTION) {
                         String folderPath = "src/main/resources/com.yoyofurniture.invoice";
                        File folder = new File(folderPath);

                        if (Desktop.isDesktopSupported()) {
                            Desktop desktop = Desktop.getDesktop();
                            try {
                                desktop.open(folder);
                            } catch (IOException ex) {
                                ex.printStackTrace();
                            }
                        }
                        ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
                    } else {
                        ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
                    }
                    
                } catch (FileNotFoundException e) {
                    throw new RuntimeException(e);
                }
            } else {
                jInvoiceError.setText("Sale Order not approved yet.");
                
            }
        } catch (Exception ex) {
            Logger.getLogger(OfcGenerateReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jGenerateInvoiceActionPerformed

    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    private void jGenerateWorkDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateWorkDoneActionPerformed
        String selectedMonth = (String) jComboBoxMonth.getSelectedItem();
        String selectedYear = (String) jComboBoxYear.getSelectedItem();
        WorkDoneReport work = new WorkDoneReport();
        
        try {
            work.generateWorkDoneReport(officer.getUserID(),selectedMonth,selectedYear);
                int confirmation = JOptionPane.showOptionDialog(this,"Work Done Report Successfully created!","Message",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,new String[]{"Open in Folder", "Close"},"Close");
        
                    if (confirmation == JOptionPane.YES_OPTION) {
                         String folderPath = "src/main/resources/com.yoyofurniture.workdonereport";
                        File folder = new File(folderPath);

                        if (Desktop.isDesktopSupported()) {
                            Desktop desktop = Desktop.getDesktop();
                            try {
                                desktop.open(folder);
                            } catch (IOException ex) {
                                ex.printStackTrace();
                            }
                        }
                        ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
                    } else {
                        ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
                    }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OfcGenerateReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jGenerateWorkDoneActionPerformed

    private void jGenerateApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateApprovedActionPerformed
        String selectedMonth = (String) jComboBoxMonth1.getSelectedItem();
        String selectedYear = (String) jComboBoxYear1.getSelectedItem();
        SaleReport salereport = new SaleReport();

        try {
            salereport.generateApprovedSaleReport(officer.getUserID(),selectedMonth,selectedYear);
            int confirmation = JOptionPane.showOptionDialog(this,"Approved Sales Report Successfully created!","Message",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,new String[]{"Open in Folder", "Close"},"Close");

            if (confirmation == JOptionPane.YES_OPTION) {
                String folderPath = "src/main/resources/com.yoyofurniture.approvedsalereport";
                File folder = new File(folderPath);

                if (Desktop.isDesktopSupported()) {
                    Desktop desktop = Desktop.getDesktop();
                    try {
                        desktop.open(folder);
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
                ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
            } else {
                ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OfcGenerateReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jGenerateApprovedActionPerformed

    private void jComboBoxMonth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonth1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonth1ActionPerformed

    private void jComboBoxMonth2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonth2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonth2ActionPerformed

    private void jGenerateClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateClosedActionPerformed
        String selectedMonth = (String) jComboBoxMonth1.getSelectedItem();
        String selectedYear = (String) jComboBoxYear1.getSelectedItem();
        SaleReport salereport = new SaleReport();
        
        try {
            salereport.generateClosedSaleReport(officer.getUserID(),selectedMonth,selectedYear);
                int confirmation = JOptionPane.showOptionDialog(this,"ClosedSales Report Successfully created!","Message",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,new String[]{"Open in Folder", "Close"},"Close");
        
                    if (confirmation == JOptionPane.YES_OPTION) {
                         String folderPath = "src/main/resources/com.yoyofurniture.closedsalereport";
                        File folder = new File(folderPath);

                        if (Desktop.isDesktopSupported()) {
                            Desktop desktop = Desktop.getDesktop();
                            try {
                                desktop.open(folder);
                            } catch (IOException ex) {
                                ex.printStackTrace();
                            }
                        }
                        ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
                    } else {
                        ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
                    }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OfcGenerateReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jGenerateClosedActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxInvoice;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxMonth1;
    private javax.swing.JComboBox<String> jComboBoxMonth2;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JComboBox<String> jComboBoxYear1;
    private javax.swing.JComboBox<String> jComboBoxYear2;
    private javax.swing.JButton jGenerateApproved;
    private javax.swing.JButton jGenerateClosed;
    private javax.swing.JButton jGenerateInvoice;
    private javax.swing.JButton jGenerateWorkDone;
    private javax.swing.JLabel jInvoiceError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jWorkDoneError;
    private javax.swing.JLabel jWorkDoneError1;
    private javax.swing.JLabel jWorkDoneError2;
    // End of variables declaration//GEN-END:variables

    private void selfInitComponents() {
        setTitle("Generate Reports");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        try {
            List<SaleOrder> salesorders = HandleSales.readAllSalesOrder();
            for (SaleOrder saleorder : salesorders) {
                jComboBoxInvoice.addItem(saleorder.toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jInvoiceError.setText("");
        jWorkDoneError.setText("");
        jWorkDoneError1.setText("");
        jWorkDoneError2.setText("");
        
        JComboBox<String> jComboBoxMonth = new JComboBox<>(new String[]{
                "January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"
        });
        
        
    }
    
    private boolean validateOrderStatus(SaleOrder saleOrder){
        return !saleOrder.getStatus().equals(Status.PENDING.getStatus()) &&
           !saleOrder.getStatus().equals(Status.UNAPPROVED.getStatus());
    }
        
    

}
