/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.yoyofurniture.gui.officer;

import com.yoyofurniture.bean.Officer;
import com.yoyofurniture.gui.Login;
import java.awt.Container;
import javax.swing.*;
import javax.swing.SwingUtilities;


public class OfcMain extends javax.swing.JPanel {
    private Officer officer;

    /**
     * Creates new form OfcMain
     */
    public OfcMain(Officer officer) {
        initComponents();
        this.officer = officer;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReport = new javax.swing.JButton();
        jButtonProcessOrder = new javax.swing.JButton();
        jButtonSubmitOrder = new javax.swing.JButton();
        jButtonViewStatus = new javax.swing.JButton();
        jButtonEditPersonal = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();

        jButtonReport.setText("Generate Reports");
        jButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportActionPerformed(evt);
            }
        });

        jButtonProcessOrder.setText("Process Sale Orders");
        jButtonProcessOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcessOrderActionPerformed(evt);
            }
        });

        jButtonSubmitOrder.setText("Submit Orders for Production");
        jButtonSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitOrderActionPerformed(evt);
            }
        });

        jButtonViewStatus.setText("View Sale Product Status");
        jButtonViewStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewStatusActionPerformed(evt);
            }
        });

        jButtonEditPersonal.setText("Edit Personal Profile");
        jButtonEditPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPersonalActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonReport)
                    .addComponent(jButtonProcessOrder)
                    .addComponent(jButtonSubmitOrder)
                    .addComponent(jButtonViewStatus)
                    .addComponent(jButtonEditPersonal)
                    .addComponent(jButtonLogout))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButtonReport)
                .addGap(27, 27, 27)
                .addComponent(jButtonProcessOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButtonSubmitOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jButtonViewStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jButtonEditPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(182, 182, 182))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPersonalActionPerformed
        OfcManagePersonal ofcManagePersonal = OfcManagePersonal.initiateOfcManagePersonal(officer);
        ofcManagePersonal.setVisible(true);
    }//GEN-LAST:event_jButtonEditPersonalActionPerformed

    private void jButtonProcessOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcessOrderActionPerformed
        enterFunction(new OfcManageOrder(officer));
    }//GEN-LAST:event_jButtonProcessOrderActionPerformed

    private void jButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportActionPerformed
        OfcGenerateReport report = new OfcGenerateReport(officer);
        report.setVisible(true);
    }//GEN-LAST:event_jButtonReportActionPerformed

    private void jButtonSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitOrderActionPerformed
        enterFunction(new OfcSubmitProduction(officer));
    }//GEN-LAST:event_jButtonSubmitOrderActionPerformed

    private void jButtonViewStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewStatusActionPerformed
        OfcCheckProductStatus statusCheck = new OfcCheckProductStatus(officer);
        statusCheck.setVisible(true);
        
        enterFunction(new OfcCheckProductStatus(officer));
    }//GEN-LAST:event_jButtonViewStatusActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.dispose();
            new Login().setVisible(true);
        }
       
    }//GEN-LAST:event_jButtonLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditPersonal;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonProcessOrder;
    private javax.swing.JButton jButtonReport;
    private javax.swing.JButton jButtonSubmitOrder;
    private javax.swing.JButton jButtonViewStatus;
    // End of variables declaration//GEN-END:variables

    private void enterFunction(JPanel jPanel) {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.getContentPane().removeAll();
            frame.setContentPane(jPanel);
            frame.getContentPane().revalidate();
            frame.getContentPane().repaint();
        }
    }
}
