package com.yoyofurniture.gui.officer;

import com.yoyofurniture.bean.Officer;
import com.yoyofurniture.utility.HandleAccount;
import java.awt.Component;

import javax.swing.*;


public class OfcManagePersonal extends javax.swing.JFrame {
    private static OfcManagePersonal currentInstance;
    private final Officer officer;


    private OfcManagePersonal(Officer officer) {
        this.officer = officer;
        initComponents();
        selfInitComponents();
        setTitle("Edit Officer Profile");
        setLocationRelativeTo(null);
    }

    /**
     * Singleton structure
     * @return OfcManagePersonal
     */
    public static OfcManagePersonal initiateOfcManagePersonal(Officer officer) {
        if (currentInstance == null) {
            currentInstance = new OfcManagePersonal(officer);
        }
        return currentInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jPasswordFieldCurrent = new javax.swing.JPasswordField();
        jPasswordFieldNew = new javax.swing.JPasswordField();
        jPasswordFieldReEnter = new javax.swing.JPasswordField();
        jButtonDiscard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jToggleButtonEnablePass = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelWarning = new javax.swing.JLabel();
        jResetButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Re-Enter New Password");

        jLabel5.setText("Enter New Password");

        jPasswordFieldCurrent.setEditable(false);

        jPasswordFieldNew.setEditable(false);

        jPasswordFieldReEnter.setEditable(false);

        jButtonDiscard.setText("Discard Changes");
        jButtonDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscardActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jButtonSave.setText("Save Changes");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTextFieldId.setEditable(false);

        jToggleButtonEnablePass.setText("Change Password");
        jToggleButtonEnablePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEnablePassActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Current Password");

        jLabel6.setText("Phone Number");

        jLabel7.setText("Email");

        jLabelWarning.setPreferredSize(new java.awt.Dimension(200, 20));

        jResetButton1.setText("Reset Changes");
        jResetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDiscard)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jResetButton1)
                        .addGap(229, 229, 229))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldName)
                                    .addComponent(jTextFieldId))
                                .addGap(245, 245, 245))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(251, 251, 251)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonEnablePass)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPasswordFieldCurrent)
                        .addComponent(jPasswordFieldNew)
                        .addComponent(jPasswordFieldReEnter))
                    .addGap(251, 251, 251)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldId))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldName))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPhone))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEmail)))
                .addGap(164, 164, 164)
                .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDiscard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResetButton1))
                .addGap(159, 159, 159))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(246, 246, 246)
                    .addComponent(jToggleButtonEnablePass)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldCurrent))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldNew))
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldReEnter))
                    .addGap(218, 218, 218)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscardActionPerformed
        int confirmation = JOptionPane.showOptionDialog(
                OfcManagePersonal.this,
                "Are you sure you want to discard changes?",
                "Discard Changes",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                new String[]{"Confirm", "Cancel"},
                "Confirm"
        );
        
        if (confirmation == JOptionPane.YES_OPTION) {
            dispose();
        } else {
            ((JDialog) SwingUtilities.getRoot((Component) evt.getSource())).dispose();
        }
        
    }//GEN-LAST:event_jButtonDiscardActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String userID = officer.getUserID();
        String name = jTextFieldName.getText();
        String phone = jTextFieldPhone.getText();
        String email = jTextFieldEmail.getText();
        String oldPassword = String.valueOf(jPasswordFieldCurrent.getPassword());
        String newPassword = String.valueOf(jPasswordFieldNew.getPassword());
        String rePassword = String.valueOf(jPasswordFieldReEnter.getPassword());

        boolean changePass = jToggleButtonEnablePass.isSelected();

        try {
            if (!validateInformation(changePass, name, phone, email, oldPassword, newPassword, rePassword)) {
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        String[] newInfo = {userID, rePassword, name, phone, email};
        Officer.savePersonal(newInfo, changePass, officer);

        // Modify current user data
        officer.setName(name);
        if (changePass) {
            officer.setPassword(HandleAccount.hashString(rePassword));
        }
        officer.setPhoneNumber(phone);
        officer.setEmail(email);
        setPasswordField(false);

        JOptionPane.showMessageDialog(this, "Profile saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        currentInstance = null;
        dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jToggleButtonEnablePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEnablePassActionPerformed
        setPasswordField(jToggleButtonEnablePass.isSelected());
    }//GEN-LAST:event_jToggleButtonEnablePassActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        currentInstance = null;
    }//GEN-LAST:event_formWindowClosed

    private void jResetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButton1ActionPerformed
        jLabelWarning.setText("");
        jTextFieldName.setText(officer.getName());
        jTextFieldPhone.setText(officer.getPhoneNumber());
        jTextFieldEmail.setText(officer.getEmail());
        jToggleButtonEnablePass.setSelected(false);
        setPasswordField(false);
    }//GEN-LAST:event_jResetButton1ActionPerformed


    /**
     * validate the information
     * @param changePass is change password enable?
     * @param name name
     * @param phone phone
     * @param email email
     * @param oldPassword old password
     * @param newPassword new password
     * @param rePassword re-enter password
     * @return true if all information correct, vice versa
     * @throws Exception exception
     */
    private boolean validateInformation(boolean changePass, String name, String phone, String email, String oldPassword, String newPassword, String rePassword) throws Exception {
        if (name.isEmpty()) {
            jLabelWarning.setText("Please enter proper name");
            return false;
        } else if (!HandleAccount.validatePhone(phone)) {
            jLabelWarning.setText("Please enter valid Malaysia phone number");
            return false;
        } else if (!HandleAccount.validateEmail(email)) {
            jLabelWarning.setText("Please enter valid email");
            return false;
        }

        // Password Validation
        if (changePass) {
            return validatePassword(oldPassword, newPassword, rePassword);
        }
        return true;
    }

    /**
     * Validate password format, and make sure re-enter password match to new password
     * @param oldPassword old password
     * @param newPassword new password
     * @param rePassword re-enter password
     * @return true if all correct, vice versa
     */
    private boolean validatePassword(String oldPassword, String newPassword, String rePassword) {
        if (!officer.getPassword().equals(HandleAccount.hashString(oldPassword))) {
            jLabelWarning.setText("Current Password is incorrect.");
        } else if (!HandleAccount.validateNewPassword(newPassword)) {
            jLabelWarning.setText("The new password must be at least 8 characters, 1 Capital Letter, and 1 symbol.");
        } else if (!HandleAccount.comparePassword(newPassword, rePassword)) {
            jLabelWarning.setText("Re-enter password does not match new password.");
        } else {
            return true;
        }
        return false; // Password validation passed
    }

    /**
     * setEnable of password field
     * @param set true to enable, false to disable
     */
    private void setPasswordField(boolean set) {
        jPasswordFieldCurrent.setEditable(set);
        jPasswordFieldNew.setEditable(set);
        jPasswordFieldReEnter.setEditable(set);

        jPasswordFieldCurrent.setText("");
        jPasswordFieldNew.setText("");
        jPasswordFieldReEnter.setText("");
    }

    private void selfInitComponents() {
        jTextFieldId.setText(officer.getUserID());
        jResetButton1ActionPerformed(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiscard;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPasswordField jPasswordFieldCurrent;
    private javax.swing.JPasswordField jPasswordFieldNew;
    private javax.swing.JPasswordField jPasswordFieldReEnter;
    private javax.swing.JButton jResetButton1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JToggleButton jToggleButtonEnablePass;
    // End of variables declaration//GEN-END:variables
}
