package com.yoyofurniture.gui.salesperson;

import com.yoyofurniture.bean.Salesperson;
import com.yoyofurniture.gui.Login;


import javax.swing.*;


public class SpMain extends javax.swing.JPanel {
    private final Salesperson salesperson;

    public SpMain(Salesperson salesperson) {
        this.salesperson = salesperson;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonManage = new javax.swing.JButton();
        jButtonEditPersonal = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();

        jButtonAdd.setText("Add Sale Order");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonManage.setText("Manage Sale List");
        jButtonManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageActionPerformed(evt);
            }
        });

        jButtonEditPersonal.setText("Edit Personal Profile");
        jButtonEditPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPersonalActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonManage)
                    .addComponent(jButtonEditPersonal)
                    .addComponent(jButtonLogout))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButtonAdd)
                .addGap(47, 47, 47)
                .addComponent(jButtonManage)
                .addGap(28, 28, 28)
                .addComponent(jButtonEditPersonal)
                .addGap(41, 41, 41)
                .addComponent(jButtonLogout)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        enterFunction(new SpAddSalesOrder(salesperson));
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageActionPerformed
        enterFunction(new SpManageOrder(salesperson));
    }//GEN-LAST:event_jButtonManageActionPerformed

    private void jButtonEditPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPersonalActionPerformed
        SpManagePersonal spManagePersonal = SpManagePersonal.initiateSpManagePersonal(salesperson);
        spManagePersonal.setVisible(true);
    }//GEN-LAST:event_jButtonEditPersonalActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed


    /**
     * Switch scene (panel)
     * @param jPanel panel to be switched
     */
    private void enterFunction(JPanel jPanel){
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.getContentPane().removeAll();
            frame.setContentPane(jPanel);
            frame.getContentPane().revalidate();
            frame.getContentPane().repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEditPersonal;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonManage;
    // End of variables declaration//GEN-END:variables
}
