package com.yoyofurniture.gui;

import com.yoyofurniture.bean.*;
import com.yoyofurniture.utility.HandleAccount;

import java.io.FileNotFoundException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class SalesOrderDetailAndInvoice extends javax.swing.JFrame {
    private final SaleOrder saleOrder;
    private Salesperson salesperson;
    private Customer customer;
    private DefaultTableModel jTableModel;

    public SalesOrderDetailAndInvoice(SaleOrder saleOrder) {
        this.saleOrder = saleOrder;
        initComponents();
        selfInintComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCust = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDateTime = new javax.swing.JLabel();
        jLabelSP = new javax.swing.JLabel();
        jLabelOrderID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jButtonInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Order ID:");

        jLabel2.setText("Status:");

        jLabel3.setText("Salesperson:");

        jLabelCust.setText("Customer ID");

        jLabel5.setText("Customer:");

        jLabelDateTime.setText("Date Time");

        jLabelSP.setText("Salesperson ID");

        jLabelOrderID.setText("Order ID");

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProduct.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableProduct);

        jLabel4.setText("Date Time:");

        jLabel6.setText("Total:");

        jLabelTotal.setText("Total");

        jLabelStatus.setText("Status");

        jButtonInvoice.setText("Invoice");
        jButtonInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSP, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCust, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCust, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvoiceActionPerformed
        Invoice invoice = new Invoice(saleOrder);

        try {
            invoice.generateInvoice(salesperson, customer);
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }

        JOptionPane.showMessageDialog(this
                , "Invoice created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
    }//GEN-LAST:event_jButtonInvoiceActionPerformed

    /**
     * insert row into table
     * @param itemID item id
     * @param itemName item name
     * @param itemPrice item price
     * @param itemQuantity item quantity
     * @param itemAmount item amount
     */
    private void insertData(String itemID, String itemName, double itemPrice, int itemQuantity, double itemAmount) {
        // Add a row with the provided data to the DefaultTableModel
        jTableModel.addRow(new Object[]{itemID, itemName, itemPrice, itemQuantity, itemAmount});
    }

    private void selfInintComponents() {
        try {
            salesperson = HandleAccount.readAllData("salesperson.txt", userinfo -> new Salesperson(userinfo[0], userinfo[1],
                            userinfo[2], userinfo[3], userinfo[4], userinfo[5], userinfo[6]), ","
                    ).stream().filter(user -> user.getUserID().equals(saleOrder.getSalesperson())).findFirst()
                    .map(user -> (Salesperson)user).get();
            customer = HandleAccount.readAllData("customer.txt", userinfo -> new Customer(userinfo[0], userinfo[1],
                            userinfo[2], userinfo[3]), "\\|"
                    ).stream().filter(user -> user.getUserID().equals(saleOrder.getCustomer())).findFirst()
                    .map(user -> (Customer)user).get();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }


        jLabelOrderID.setText(saleOrder.getSaleID());
        jLabelSP.setText(salesperson.getName());
        jLabelCust.setText(customer.getName());
        jLabelDateTime.setText(saleOrder.getSaleDateTime());
        jLabelStatus.setText(saleOrder.getStatus());
        jLabelTotal.setText(saleOrder.getTotal()+"");
        
        setTitle("SaleOrder Details (ID:"+saleOrder.getSaleID()+")");
        setLocationRelativeTo(null);

        jTableModel = new DefaultTableModel(new Object[]{"ID", "Name", "Price", "Quantity", "Amount"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTableProduct.setModel(jTableModel);

        saleOrder.getProductList().forEach(selectedProduct
                -> insertData(selectedProduct.getProduct().getItemID(), selectedProduct.getProduct().getItemName(),
                selectedProduct.getProduct().getItemPrice(), selectedProduct.getQuantity(), selectedProduct.getAmount()));

        if (saleOrder.getStatus().equals(Status.PENDING.getStatus()) ||
                saleOrder.getStatus().equals(Status.UNAPPROVED.getStatus())){
            jButtonInvoice.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInvoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCust;
    private javax.swing.JLabel jLabelDateTime;
    private javax.swing.JLabel jLabelOrderID;
    private javax.swing.JLabel jLabelSP;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduct;
    // End of variables declaration//GEN-END:variables
}
